
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace global
[<assembly: Android.Runtime.ResourceDesignerAttribute("PitOfDespair.Resource", IsApplication=true)>]
    do ()

namespace PitOfDespair
    // Generated by F# CodeDom
    #nowarn "49" // uppercase argument names
    #nowarn "67" // this type test or downcast will always hold
    #nowarn "66" // this upcast is unnecessary - the types are identical
    #nowarn "58" // possible incorrect indentation..
    #nowarn "57" // do not use create_DelegateEvent
    #nowarn "51" // address-of operator can occur in the code
    #nowarn "1183" // unused 'this' reference
    
    exception ReturnException80346cf2eab34f988744e4f5df55fc5c of obj
    exception ReturnNoneException80346cf2eab34f988744e4f5df55fc5c
    [<AutoOpen>]
    module FuncConvertFinalOverload80346cf2eab34f988744e4f5df55fc5c =
      // This extension member adds to the FuncConvert type and is the last resort member in the method overloading rules. 
      type global.Microsoft.FSharp.Core.FuncConvert with
          /// A utility function to convert function values from tupled to curried form
          static member FuncFromTupled (f:'T -> 'Res) = f
    
    type
        [<System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")>]
        
        (* partial *)Resource () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)
            static member UpdateIdValues  () =
                ()


    
    and
        
        (* partial *)Resource_Attribute () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Drawable () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f020000
            static member Icon = 2130837504
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Id () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f05000f
            static member btnAchievements = 2131034127
            
            // aapt resource value: 0x7f050010
            static member btnAdventure = 2131034128
            
            // aapt resource value: 0x7f050000
            static member btnAdventurer = 2131034112
            
            // aapt resource value: 0x7f05000d
            static member btnChooser = 2131034125
            
            // aapt resource value: 0x7f05000e
            static member btnInventory = 2131034126
            
            // aapt resource value: 0x7f050001
            static member btnWarrior = 2131034113
            
            // aapt resource value: 0x7f050005
            static member editText1 = 2131034117
            
            // aapt resource value: 0x7f050006
            static member editText2 = 2131034118
            
            // aapt resource value: 0x7f050004
            static member imagePortrait = 2131034116
            
            // aapt resource value: 0x7f050003
            static member linearLayout1 = 2131034115
            
            // aapt resource value: 0x7f050002
            static member relativeLayout1 = 2131034114
            
            // aapt resource value: 0x7f050007
            static member tableLayout1 = 2131034119
            
            // aapt resource value: 0x7f050008
            static member tableRow1 = 2131034120
            
            // aapt resource value: 0x7f050009
            static member tableRow2 = 2131034121
            
            // aapt resource value: 0x7f05000c
            static member tableRow3 = 2131034124
            
            // aapt resource value: 0x7f05000b
            static member tableRow4 = 2131034123
            
            // aapt resource value: 0x7f05000a
            static member tableRow5 = 2131034122
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Layout () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f030000
            static member Classes = 2130903040
            
            // aapt resource value: 0x7f030001
            static member Dungeon = 2130903041
            
            // aapt resource value: 0x7f030002
            static member Main = 2130903042
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_String () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f040002
            static member app_name = 2130968578
            
            // aapt resource value: 0x7f040000
            static member hello = 2130968576
            
            // aapt resource value: 0x7f040001
            static member hello2 = 2130968577
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)

